### ISSUE TITLE
Can't Install Without Being Root

### ISSUE THREAD

**Issue by brotatos** [wbsun/kgpu#3]
I was tr ying to install this without invoking sudo but I was unable to using the PKGBUILD [1] I wrote.

[1] http://sprunge.us/MPgP?bash

**Comment by wbsun** [comment]
KGPU makefile is simple, it doesn't have a real 'install' target. It is great to see you wrote that script for KGPU. Though I am not familiar with it, but looks like you should copy the kernel modules built by KGPU makefile to /lib/modules/`uname -r`/somewhere . And the userspace helper executable and service libs starting with 'libsrv_' to common UNIX locations such as /usr/bin /usr/lib. By the way, the helper executable needs a command line arguments to specify service libs location if they are not in the same directory.
